[package]
name = "partial_eq_refs"
edition.workspace = true
repository.workspace = true
license.workspace = true
version.workspace = true
authors.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = "1.0"

[lints]
workspace = true
